root: true
env:
  commonjs: true
  shared-node-browser: true
  node: true
  es2021: true
  jest: true
parser: "@typescript-eslint/parser"
plugins:
    - "@typescript-eslint"
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
rules:
    no-await-in-loop: warn
    no-unreachable: warn
    prefer-const: warn
    semi:
        - error
        - always
    linebreak-style:
        - error
        - unix
    indent:
        - error
        - tab
        - SwitchCase: 1
          outerIIFEBody: 1
    '@typescript-eslint/ban-ts-comment':
        - error
        - ts-ignore: "allow-with-description"
          ts-nocheck: "allow-with-description"
          ts-expect-error: "allow-with-description"
    '@typescript-eslint/no-inferrable-types': 0

